# version: '3.8'

services:
  app:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=rm-bp1h1uj8tk619834plo.mysql.rds.aliyuncs.com
      - DB_PORT=3306
      - DB_USERNAME=dms_user_ea9646c
      - DB_PASSWORD=Chai826300474
      - DB_DATABASE=db_template
      # PM2配置 - 实例数量
      - PM2_INSTANCES=max
      # PM2配置 - 内存限制
      - PM2_MAX_MEMORY_RESTART=1G
    restart: always
    # 为PM2日志创建数据卷
    volumes:
      - /root/.pm2/logs:/root/.pm2/logs
      - /var/www/static:/static